
package pe.gob.sunat.service.bzlinks.beta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bizlinksOSE", targetNamespace = "http://service.sunat.gob.pe", wsdlLocation = "https://testose2.bizlinks.com.pe/ol-ti-itcpe/billService?wsdl")
public class BizlinksOSE
    extends Service
{

    private final static URL BIZLINKSOSE_WSDL_LOCATION;
    private final static WebServiceException BIZLINKSOSE_EXCEPTION;
    private final static QName BIZLINKSOSE_QNAME = new QName("http://service.sunat.gob.pe", "bizlinksOSE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://testose2.bizlinks.com.pe/ol-ti-itcpe/billService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIZLINKSOSE_WSDL_LOCATION = url;
        BIZLINKSOSE_EXCEPTION = e;
    }

    public BizlinksOSE() {
        super(__getWsdlLocation(), BIZLINKSOSE_QNAME);
    }

    public BizlinksOSE(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIZLINKSOSE_QNAME, features);
    }

    public BizlinksOSE(URL wsdlLocation) {
        super(wsdlLocation, BIZLINKSOSE_QNAME);
    }

    public BizlinksOSE(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIZLINKSOSE_QNAME, features);
    }

    public BizlinksOSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BizlinksOSE(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillServicePort
     */
    @WebEndpoint(name = "BillServicePortSoap11")
    public BillServicePort getBillServicePortSoap11() {
        return super.getPort(new QName("http://service.sunat.gob.pe", "BillServicePortSoap11"), BillServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillServicePort
     */
    @WebEndpoint(name = "BillServicePortSoap11")
    public BillServicePort getBillServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sunat.gob.pe", "BillServicePortSoap11"), BillServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIZLINKSOSE_EXCEPTION!= null) {
            throw BIZLINKSOSE_EXCEPTION;
        }
        return BIZLINKSOSE_WSDL_LOCATION;
    }

}
