
package pe.com.grupopalomino.sistema.boletaje.visarespuesta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Consultas en Linea resultado de la transacción
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSConsultaEticket", targetNamespace = "https://www.multimerchantvisanet.com/ConsultaEnLineaEticket", wsdlLocation = "https://www.multimerchantvisanet.com/WSConsulta/WSConsultaEticket.asmx?wsdl")
public class WSConsultaEticket
    extends Service
{

    private final static URL WSCONSULTAETICKET_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTAETICKET_EXCEPTION;
    private final static QName WSCONSULTAETICKET_QNAME = new QName("https://www.multimerchantvisanet.com/ConsultaEnLineaEticket", "WSConsultaEticket");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.multimerchantvisanet.com/WSConsulta/WSConsultaEticket.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTAETICKET_WSDL_LOCATION = url;
        WSCONSULTAETICKET_EXCEPTION = e;
    }

    public WSConsultaEticket() {
        super(__getWsdlLocation(), WSCONSULTAETICKET_QNAME);
    }

    public WSConsultaEticket(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTAETICKET_QNAME, features);
    }

    public WSConsultaEticket(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTAETICKET_QNAME);
    }

    public WSConsultaEticket(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTAETICKET_QNAME, features);
    }

    public WSConsultaEticket(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSConsultaEticket(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSConsultaEticketSoap
     */
    @WebEndpoint(name = "WSConsultaEticketSoap")
    public WSConsultaEticketSoap getWSConsultaEticketSoap() {
        return super.getPort(new QName("https://www.multimerchantvisanet.com/ConsultaEnLineaEticket", "WSConsultaEticketSoap"), WSConsultaEticketSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSConsultaEticketSoap
     */
    @WebEndpoint(name = "WSConsultaEticketSoap")
    public WSConsultaEticketSoap getWSConsultaEticketSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.multimerchantvisanet.com/ConsultaEnLineaEticket", "WSConsultaEticketSoap"), WSConsultaEticketSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTAETICKET_EXCEPTION!= null) {
            throw WSCONSULTAETICKET_EXCEPTION;
        }
        return WSCONSULTAETICKET_WSDL_LOCATION;
    }

}
