
package pe.com.grupopalomino.sistema.boletaje.visa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSEticketSoap", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEticketSoap {


    /**
     * Solicitar pedido - Generacion de Eticket
     * 
     * @param xmlIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraEticket", action = "https://www.multimerchantvisanet.com/solicitudtransaccion/GeneraEticket")
    @WebResult(name = "GeneraEticketResult", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion")
    @RequestWrapper(localName = "GeneraEticket", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion", className = "https.www_multimerchantvisanet_com.solicitudtransaccion.GeneraEticket")
    @ResponseWrapper(localName = "GeneraEticketResponse", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion", className = "https.www_multimerchantvisanet_com.solicitudtransaccion.GeneraEticketResponse")
    public String generaEticket(
        @WebParam(name = "xmlIn", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion")
        String xmlIn);

}
