
package pe.com.grupopalomino.sistema.boletaje.visa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Consultas en Linea de transacciones
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSEticket", targetNamespace = "https://www.multimerchantvisanet.com/solicitudtransaccion", wsdlLocation = "https://www.multimerchantvisanet.com/WSGenerarEticket/WSEticket.asmx?wsdl")
public class WSEticket
    extends Service
{

    private final static URL WSETICKET_WSDL_LOCATION;
    private final static WebServiceException WSETICKET_EXCEPTION;
    private final static QName WSETICKET_QNAME = new QName("https://www.multimerchantvisanet.com/solicitudtransaccion", "WSEticket");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.multimerchantvisanet.com/WSGenerarEticket/WSEticket.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSETICKET_WSDL_LOCATION = url;
        WSETICKET_EXCEPTION = e;
    }

    public WSEticket() {
        super(__getWsdlLocation(), WSETICKET_QNAME);
    }

    public WSEticket(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSETICKET_QNAME, features);
    }

    public WSEticket(URL wsdlLocation) {
        super(wsdlLocation, WSETICKET_QNAME);
    }

    public WSEticket(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSETICKET_QNAME, features);
    }

    public WSEticket(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEticket(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSEticketSoap
     */
    @WebEndpoint(name = "WSEticketSoap")
    public WSEticketSoap getWSEticketSoap() {
        return super.getPort(new QName("https://www.multimerchantvisanet.com/solicitudtransaccion", "WSEticketSoap"), WSEticketSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEticketSoap
     */
    @WebEndpoint(name = "WSEticketSoap")
    public WSEticketSoap getWSEticketSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.multimerchantvisanet.com/solicitudtransaccion", "WSEticketSoap"), WSEticketSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSETICKET_EXCEPTION!= null) {
            throw WSETICKET_EXCEPTION;
        }
        return WSETICKET_WSDL_LOCATION;
    }

}
