
package pe.com.grupopalomino.sistema.boletaje.pagoefectivo.sources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.BEWSConsultarCIPResponseMod1
     */
    @WebMethod(operationName = "ConsultarCIPMod1", action = "http://tempuri.org/ConsultarCIPMod1")
    @WebResult(name = "ConsultarCIPMod1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarCIPMod1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCIPMod1")
    @ResponseWrapper(localName = "ConsultarCIPMod1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCIPMod1Response")
    public BEWSConsultarCIPResponseMod1 consultarCIPMod1(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        BEWSConsultarCIPRequestMod1 request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.BEWSActualizaCIPResponseMod1
     */
    @WebMethod(operationName = "ActualizarCIPMod1", action = "http://tempuri.org/ActualizarCIPMod1")
    @WebResult(name = "ActualizarCIPMod1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarCIPMod1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizarCIPMod1")
    @ResponseWrapper(localName = "ActualizarCIPMod1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizarCIPMod1Response")
    public BEWSActualizaCIPResponseMod1 actualizarCIPMod1(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        BEWSActualizaCIPRequestMod1 request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.BEWSElimCIPResponseMod1
     */
    @WebMethod(operationName = "EliminarCIPMod1", action = "http://tempuri.org/EliminarCIPMod1")
    @WebResult(name = "EliminarCIPMod1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarCIPMod1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarCIPMod1")
    @ResponseWrapper(localName = "EliminarCIPMod1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarCIPMod1Response")
    public BEWSElimCIPResponseMod1 eliminarCIPMod1(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        BEWSElimCIPRequestMod1 request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.BEWSGenCIPResponseMod1
     */
    @WebMethod(operationName = "GenerarCIPMod1", action = "http://tempuri.org/GenerarCIPMod1")
    @WebResult(name = "GenerarCIPMod1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerarCIPMod1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarCIPMod1")
    @ResponseWrapper(localName = "GenerarCIPMod1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarCIPMod1Response")
    public BEWSGenCIPResponseMod1 generarCIPMod1(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        BEWSGenCIPRequestMod1 request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.BEWSConsultarSolicitudResponse
     */
    @WebMethod(operationName = "ConsultarSolicitudPagov2", action = "http://tempuri.org/ConsultarSolicitudPagov2")
    @WebResult(name = "ConsultarSolicitudPagov2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarSolicitudPagov2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarSolicitudPagov2")
    @ResponseWrapper(localName = "ConsultarSolicitudPagov2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarSolicitudPagov2Response")
    public BEWSConsultarSolicitudResponse consultarSolicitudPagov2(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        BEWSConsultarSolicitudRequest request);

}
