
package pe.com.grupopalomino.sistema.boletaje.pagoefectivo.sources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCIP", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources/WSCIP.asmx.xml")
public class WSCIP
    extends Service
{

    private final static URL WSCIP_WSDL_LOCATION;
    private final static WebServiceException WSCIP_EXCEPTION;
    private final static QName WSCIP_QNAME = new QName("http://tempuri.org/", "WSCIP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources/WSCIP.asmx.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCIP_WSDL_LOCATION = url;
        WSCIP_EXCEPTION = e;
    }

    public WSCIP() {
        super(__getWsdlLocation(), WSCIP_QNAME);
    }

    public WSCIP(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCIP_QNAME, features);
    }

    public WSCIP(URL wsdlLocation) {
        super(wsdlLocation, WSCIP_QNAME);
    }

    public WSCIP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCIP_QNAME, features);
    }

    public WSCIP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCIP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCIPSoap
     */
    @WebEndpoint(name = "WSCIPSoap")
    public WSCIPSoap getWSCIPSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WSCIPSoap"), WSCIPSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCIPSoap
     */
    @WebEndpoint(name = "WSCIPSoap")
    public WSCIPSoap getWSCIPSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSCIPSoap"), WSCIPSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCIP_EXCEPTION!= null) {
            throw WSCIP_EXCEPTION;
        }
        return WSCIP_WSDL_LOCATION;
    }

}
