
package pe.com.grupopalomino.sistema.boletaje.pagoefectivo.sources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * /opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources
 * /opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources
 */
@WebServiceClient(name = "WSCrypto", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources/WSCrypto.asmx.xml")
public class WSCrypto
    extends Service
{

    private final static URL WSCRYPTO_WSDL_LOCATION;
    private final static WebServiceException WSCRYPTO_EXCEPTION;
    private final static QName WSCRYPTO_QNAME = new QName("http://tempuri.org/", "WSCrypto");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/opt/apache-tomcat-7.0.76/webapps/ventas/WEB-INF/classes/pe/com/grupopalomino/sistema/boletaje/pagoefectivo/sources/WSCrypto.asmx.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCRYPTO_WSDL_LOCATION = url;
        WSCRYPTO_EXCEPTION = e;
    }

    public WSCrypto() {
        super(__getWsdlLocation(), WSCRYPTO_QNAME);
    }

    public WSCrypto(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCRYPTO_QNAME, features);
    }

    public WSCrypto(URL wsdlLocation) {
        super(wsdlLocation, WSCRYPTO_QNAME);
    }

    public WSCrypto(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCRYPTO_QNAME, features);
    }

    public WSCrypto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCrypto(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCryptoSoap
     */
    @WebEndpoint(name = "WSCryptoSoap")
    public WSCryptoSoap getWSCryptoSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WSCryptoSoap"), WSCryptoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCryptoSoap
     */
    @WebEndpoint(name = "WSCryptoSoap")
    public WSCryptoSoap getWSCryptoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSCryptoSoap"), WSCryptoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCRYPTO_EXCEPTION!= null) {
            throw WSCRYPTO_EXCEPTION;
        }
        return WSCRYPTO_WSDL_LOCATION;
    }

}
